export enum Genre {
  Action = 1,
  Adventure = 2,
  Animation = 3,
  Comedy = 4,
  Crime = 5,
  Documentary = 6,
  Drama = 7,
  Family = 8,
  Fantasy = 9,
  History = 10,
  Horror = 11,
  Music = 12,
  Mystery = 13,
  Romance = 14,
  ScienceFiction = 15,
  Thriller = 17,
  War = 18,
  Western = 19,
  Kids = 21,
  News = 22,
  Reality = 23,
  Talk = 26,
  GameShow = 28,
  Sports = 29,
  Adult = 30,
  Biography = 31,
  Musical = 32,
  Anime = 33,
  Food = 34,
  Travel = 35,
  Nature = 36,
  Supernatural = 37,
  TVMovie = 38,
  ActionAndAdventure = 39,
  SciFiAndFantasy = 40,
  WarAndPolitics = 41,
  Soap = 25,
}

export const GENRE_LIST: { id: Genre; name: string }[] = [
  { id: Genre.Action, name: "Action" },
  { id: Genre.ActionAndAdventure, name: "Action & Adventure" },
  { id: Genre.Adult, name: "Adult" },
  { id: Genre.Adventure, name: "Adventure" },
  { id: Genre.Animation, name: "Animation" },
  { id: Genre.Anime, name: "Anime" },
  { id: Genre.Biography, name: "Biography" },
  { id: Genre.Comedy, name: "Comedy" },
  { id: Genre.Crime, name: "Crime" },
  { id: Genre.Documentary, name: "Documentary" },
  { id: Genre.Drama, name: "Drama" },
  { id: Genre.Family, name: "Family" },
  { id: Genre.Fantasy, name: "Fantasy" },
  { id: Genre.Food, name: "Food" },
  { id: Genre.GameShow, name: "Game Show" },
  { id: Genre.History, name: "History" },
  { id: Genre.Horror, name: "Horror" },
  { id: Genre.Kids, name: "Kids" },
  { id: Genre.Music, name: "Music" },
  { id: Genre.Musical, name: "Musical" },
  { id: Genre.Mystery, name: "Mystery" },
  { id: Genre.Nature, name: "Nature" },
  { id: Genre.News, name: "News" },
  { id: Genre.Reality, name: "Reality" },
  { id: Genre.Romance, name: "Romance" },
  { id: Genre.SciFiAndFantasy, name: "Sci-Fi & Fantasy" },
  { id: Genre.ScienceFiction, name: "Science Fiction" },
  { id: Genre.Soap, name: "Soap" },
  { id: Genre.Sports, name: "Sports" },
  { id: Genre.Supernatural, name: "Supernatural" },
  { id: Genre.Talk, name: "Talk" },
  { id: Genre.Thriller, name: "Thriller" },
  { id: Genre.Travel, name: "Travel" },
  { id: Genre.TVMovie, name: "TV Movie" },
  { id: Genre.War, name: "War" },
  { id: Genre.WarAndPolitics, name: "War & Politics" },
  { id: Genre.Western, name: "Western" },
];
